---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start service
      ansible.builtin.service:
        name : apache2
        state: started
        enabled: yes

- name: Dbserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mysql-server
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Start mysql service
      ansible.builtin.service:
        name: mysql-server
        state: start
        enabled: yes




